version: '3'

services:

### Piwik Container ##################################

  analytics:
    image: piwik:fpm
    container_name: analytics
    networks:
      - worldbrain
    volumes:
      - "${PIWIK_CONF_PATH}:/var/www/html/config"
    depends_on:
      - db

### MariaDB Container ##################################

  db:
    image: mariadb
    container_name: db
    networks:
      - worldbrain
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

### Networks Setup ############################################

networks:
  worldbrain:
    driver: "bridge"
