version: '2'

services:

### Nginx Proxy Container ##################################

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "${NGINX_CONF_PATH}:/etc/nginx/nginx.conf:ro"
      - "${NGINX_SSL_PATH}:/etc/ssl:ro"
    volumes_from:
      - analytics
    networks:
      - worldbrain
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - analytics
    restart: always

### Piwik Container ##################################

  analytics:
    image: piwik:fpm
    container_name: analytics
    networks:
      - worldbrain
    volumes:
      - "${PIWIK_CONF_PATH}:/var/www/html/config"
    depends_on:
      - db
    restart: always

### MariaDB Container ##################################

  db:
    image: mariadb
    container_name: db
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    networks:
      - worldbrain
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always

### Networks Setup ############################################

networks:
  worldbrain:
    driver: "bridge"
